version: "3"

services:
  postgres:
    image: postgres:16-alpine3.20
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: concurrency
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.1-alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"


